//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdemo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcdemoEntities : DbContext
    {
        public mvcdemoEntities()
            : base("name=mvcdemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_IMG> TBL_IMG { get; set; }
        public virtual DbSet<tbl_mvcdemo> tbl_mvcdemo { get; set; }
        public virtual DbSet<tbl_validater> tbl_validater { get; set; }
        public virtual DbSet<tbl_forsearch> tbl_forsearch { get; set; }
        public virtual DbSet<ChartData> ChartDatas { get; set; }

        public System.Data.Entity.DbSet<mvcdemo.Models.mvcdemoModel> mvcdemoModels { get; set; }
    }
}
