//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_forsearch
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Number { get; set; }
    }
}
